CREATE DATABASE NHAHANG
GO
USE NHAHANG
GO

-----------------------------------------------------------------------
--KHÁCH HÀNG
CREATE TABLE KHACHHANG(
	MAKH INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	HOTEN VARCHAR(50) NOT NULL,
	SDT VARCHAR(50) NOT NULL,
	NGAYSINH DATE NOT NULL,
	GIOITINH VARCHAR(50) NOT NULL,
	NGAYDANGKY DATE NOT NULL,
	DIACHI VARCHAR(50)
)

-----------------------------------------------------------------------
--NHÂN VIÊN
CREATE TABLE NHANVIEN(
	MANV VARCHAR(50) NOT NULL PRIMARY KEY,
	HOTEN VARCHAR(50) NOT NULL,
	SDT VARCHAR(50) NOT NULL,
	NGAYSINH DATE NOT NULL,
	GIOITINH VARCHAR(50) NOT NULL,
	DIACHI VARCHAR(50) NOT NULL,
	LUONG MONEY NOT NULL
)

-----------------------------------------------------------------------
--NHÀ CUNG CẤP
CREATE TABLE NHACUNGCAP(
	MA_CUNGCAP INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	TEN VARCHAR(50) NOT NULL,
	SDT VARCHAR(50) NOT NULL,
	DIACHI VARCHAR(50) NOT NULL
)

----------------------------------------------------------------------
--MÓN ĂN
CREATE TABLE MON_AN(
	TEN_MON_AN VARCHAR(50) PRIMARY KEY,
	GIA MONEY NOT NULL
)

-----------------------------------------------------------------------
--NGUYÊN LIỆU
CREATE TABLE NGUYENLIEU(
	TEN_NGUYEN_LIEU VARCHAR(50) PRIMARY KEY,
	MA_CUNGCAP INT REFERENCES NHACUNGCAP ON UPDATE CASCADE,
)

-----------------------------------------------------------------------
--CÔNG THỨC
CREATE TABLE CONGTHUC(
	MA_CONGTHUC INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	TEN_MON_AN VARCHAR(50) REFERENCES MON_AN ON UPDATE CASCADE,
	TEN_NGUYEN_LIEU VARCHAR(50) REFERENCES NGUYENLIEU ON UPDATE CASCADE
)

-----------------------------------------------------------------------
--KHO HÀNG
CREATE TABLE KHOHANG(
	TEN_NGUYEN_LIEU VARCHAR(50) PRIMARY KEY REFERENCES NGUYENLIEU ON UPDATE CASCADE,
	DON_VI VARCHAR(50) NOT NULL,
	SOLUONG INT NOT NULL
)

-----------------------------------------------------------------------
--CHI TIÊU
CREATE TABLE CHI_TIEU(
	MA_CHI_TIEU INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	THOIGIAN DATETIME NOT NULL,
	MANV VARCHAR(50) REFERENCES NHANVIEN ON UPDATE CASCADE,
	TEN_NGUYEN_LIEU VARCHAR(50) REFERENCES NGUYENLIEU ON UPDATE CASCADE,
	DON_VI VARCHAR(50) NOT NULL,
	SOLUONG INT NOT NULL,
	GIA MONEY NOT NULL
)

-----------------------------------------------------------------------
--BÀN
CREATE TABLE BAN(
	MABAN INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	GHE INT NOT NULL,
	TANG INT NOT NULL,
	CUA_SO BIT NOT NULL
)

-----------------------------------------------------------------------
--CHI TIẾT BÀN
CREATE TABLE CHI_TIET_BAN(
	MABAN INT REFERENCES BAN ON UPDATE CASCADE,
	NGAY DATE NOT NULL,
	THOIGIAN TIME NOT NULL,
	TINHTRANG BIT NOT NULL
	CONSTRAINT PK_CTB PRIMARY KEY(MABAN, NGAY, THOIGIAN)
)

-----------------------------------------------------------------------
--ĐẶT BÀN
CREATE TABLE DATBAN(
	MA_DAT_BAN INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	MABAN INT REFERENCES BAN ON UPDATE CASCADE,
	MAKH INT REFERENCES KHACHHANG ON UPDATE CASCADE,
	NGAY DATE NOT NULL,
	THOIGIAN TIME NOT NULL,
)

-----------------------------------------------------------------------
--CA LÀM
CREATE TABLE CA_LAM(
	MA_CA_LAM INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NGAY_BATDAU DATE NOT NULL,
	NGAY_KETTHUC DATE NOT NULL,
	CA VARCHAR(50) NOT NULL
)

-----------------------------------------------------------------------
--CA LÀM NHÂN VIÊN
CREATE TABLE CA_LAM_NHAN_VIEN(
	ID_CLNV INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	MANV VARCHAR(50) REFERENCES NHANVIEN ON UPDATE CASCADE,
	MA_CA_LAM INT REFERENCES CA_LAM ON UPDATE CASCADE
)

-----------------------------------------------------------------------
--NGÀY NGHỈ
CREATE TABLE NGAYNGHI(
	ID_NN INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	MANV VARCHAR(50) REFERENCES NHANVIEN ON UPDATE CASCADE,
	NGAY_NGHI DATE NOT NULL,
	CA_NGHI VARCHAR(50) NOT NULL
)

-----------------------------------------------------------------------
--COUPON
CREATE TABLE COUPON(
	MA_COUPON VARCHAR(50) PRIMARY KEY,
	GIAM_GIA FLOAT NOT NULL,
	TIEN_TOI_THIEU MONEY NOT NULL,
	TG_BATDAU DATE,
	TG_KETTHUC DATE,
	SD_TOI_DA INT
)

-----------------------------------------------------------------------
--COUPON ĐÃ SỬ DỤNG
CREATE TABLE COUPON_DA_SU_DUNG(
	MAKH INT REFERENCES KHACHHANG ON UPDATE CASCADE,
	MA_COUPON VARCHAR(50) REFERENCES COUPON ON UPDATE CASCADE,
	SO_LAN INT NOT NULL
	CONSTRAINT PK_CDSD PRIMARY KEY(MAKH, MA_COUPON)
)

-----------------------------------------------------------------------
--HÓA ĐƠN
CREATE TABLE HOADON(
	MAHD INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	THOIGIAN DATETIME NOT NULL,
	MABAN INT REFERENCES BAN ON UPDATE CASCADE,
	MAKH INT REFERENCES KHACHHANG ON UPDATE CASCADE,
	MANV VARCHAR(50) REFERENCES NHANVIEN ON UPDATE CASCADE,
	TRIGIA_TRUOC_GIAM_GIA MONEY NOT NULL,
	MA_COUPON VARCHAR(50) REFERENCES COUPON ON UPDATE CASCADE,
	TRIGIA_SAU_GIAM_GIA MONEY NOT NULL
)

-----------------------------------------------------------------------
--CHI TIẾT HÓA ĐƠN
CREATE TABLE CTHD(
	MAHD INT REFERENCES HOADON ON UPDATE CASCADE,
	TEN_MON_AN VARCHAR(50) REFERENCES MON_AN ON UPDATE CASCADE,
	SOLUONG INT NOT NULL
	CONSTRAINT PK_CTHD PRIMARY KEY(MAHD, TEN_MON_AN)
)

-----------------------------------------------------------------------
--HÓA ĐƠN BACK UP
CREATE TABLE HOADON_BACKUP(
	MAHD_B INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	MAKH INT REFERENCES KHACHHANG ON UPDATE CASCADE,
	THOIGIAN DATETIME NOT NULL,
	TRIGIA MONEY NOT NULL
)

-----------------------------------------------------------------------
--THAY ĐỔI
CREATE TABLE THAY_DOI(
	ID_TD INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	TEN_MON_AN VARCHAR(50),
	MUC VARCHAR(50),
	DU_LIEU_CU VARCHAR(50),
	DU_LIEU_MOI VARCHAR(50),
	THOIGIAN DATETIME
)
