--PROCEDURE

--1. TÌM XEM COUPON NÀO CÓ THỂ SỬ DỤNG
CREATE OR ALTER PROCEDURE TIM_COUPON
@MAKH VARCHAR(50),
@THOIGIAN DATETIME,
@TRIGIA MONEY,
@PHUONGTHUC VARCHAR(50)
AS
	IF @PHUONGTHUC IS NOT NULL
		BEGIN
			SELECT * FROM COUPON_DA_SU_DUNG 
			FULL JOIN COUPON ON COUPON_DA_SU_DUNG.MA_COUPON = COUPON.MA_COUPON
			WHERE COUPON_DA_SU_DUNG.MAKH = @MAKH 
			AND @TRIGIA >= TIEN_TOI_THIEU
			AND @THOIGIAN BETWEEN TG_BATDAU AND TG_KETTHUC
			AND SD_TOI_DA > SO_LAN 
			AND CHARINDEX(@PHUONGTHUC, COUPON.MA_COUPON) > 0
		END	
	ELSE
		BEGIN 
			SELECT * FROM COUPON_DA_SU_DUNG 
			FULL JOIN COUPON ON COUPON_DA_SU_DUNG.MA_COUPON = COUPON.MA_COUPON
			WHERE COUPON_DA_SU_DUNG.MAKH = @MAKH 
			AND @TRIGIA >= TIEN_TOI_THIEU
			AND @THOIGIAN BETWEEN TG_BATDAU AND TG_KETTHUC
			AND SD_TOI_DA > SO_LAN 	
		END


--2. XEM CA NÀY CÓ NHỮNG NHÂN VIÊN NÀO LÀM
CREATE OR ALTER PROCEDURE TIM_NHAN_VIEN
@NGAY DATE,
@CA VARCHAR(50)
AS
	SELECT NHANVIEN.MANV, HOTEN, SDT
	FROM CA_LAM_NHAN_VIEN JOIN CA_LAM ON CA_LAM.MA_CA_LAM = CA_LAM_NHAN_VIEN.MA_CA_LAM JOIN NHANVIEN ON CA_LAM_NHAN_VIEN.MANV = NHANVIEN.MANV
	WHERE @NGAY BETWEEN NGAY_BATDAU AND NGAY_KETTHUC
	AND CA = @CA 
	AND NHANVIEN.MANV NOT IN (SELECT MANV FROM NGAYNGHI WHERE NGAY_NGHI = @NGAY AND CA = @CA)


--3. CHUYỂN HÓA ĐƠN SANG HÓA ĐƠN BACKUP
CREATE OR ALTER PROCEDURE CHUYEN_HOADON
@NGAY DATE
AS
	DECLARE CursorHoaDonBackup CURSOR
	FOR 
	SELECT MAHD, THOIGIAN, MAKH, TRIGIA_SAU_GIAM_GIA
	FROM HOADON

	OPEN CursorHoaDonBackup 
		DECLARE @MAHD INT, @THOIGIAN DATETIME, @MAKH INT, @TRIGIA MONEY
		FETCH NEXT FROM CursorHoaDonBackup INTO @MAHD, @THOIGIAN, @MAKH, @TRIGIA

		WHILE @@FETCH_STATUS = 0 
			BEGIN 
				IF @THOIGIAN < @NGAY
					BEGIN 
						INSERT INTO HOADON_BACKUP VALUES(@MAKH, @THOIGIAN, @TRIGIA)
						DELETE FROM CTHD WHERE MAHD = @MAHD
						DELETE FROM HOADON WHERE MAHD = @MAHD
					END
					FETCH NEXT FROM CursorHoaDonBackup INTO @MAHD, @THOIGIAN, @MAKH, @TRIGIA
			END

	CLOSE CursorHoaDonBackup	
	DEALLOCATE CursorHoaDonBackup


--4. TĂNG GIÁ MÓN ĂN BÁN CHẠY NHẤT
CREATE OR ALTER PROCEDURE TANG_GIA_MON_AN
@TANG_GIA MONEY
AS
	UPDATE MON_AN
		SET GIA = GIA + @TANG_GIA
		WHERE TEN_MON_AN IN (SELECT TOP(1) TEN_MON_AN FROM CTHD 
							 GROUP BY TEN_MON_AN 
							 ORDER BY SUM(SOLUONG) DESC)


--5. XEM NGÀY VÀ GIỜ NÀY CÓ BÀN NÀO CÒN TRỐNG 
CREATE OR ALTER PROCEDURE TIM_BAN
@NGAY DATE,
@THOIGIAN TIME,
@GHE INT
AS
	IF @GHE IS NULL
		BEGIN
			SELECT * FROM BAN JOIN CHI_TIET_BAN ON CHI_TIET_BAN.MABAN = BAN.MABAN
			WHERE @NGAY = CHI_TIET_BAN.NGAY AND @THOIGIAN = CHI_TIET_BAN.THOIGIAN
			AND TINHTRANG = 0
		END
	ELSE
		BEGIN
			SELECT * FROM BAN JOIN CHI_TIET_BAN ON CHI_TIET_BAN.MABAN = BAN.MABAN
			WHERE @NGAY = CHI_TIET_BAN.NGAY AND @THOIGIAN = CHI_TIET_BAN.THOIGIAN
			AND GHE >= @GHE
			AND TINHTRANG = 0
		END
