--TRIGGER

--1. TÍNH TRỊ GIÁ SAU KHI GIẢM GIÁ CỦA HÓA ĐƠN 
CREATE OR ALTER TRIGGER TINH_HOA_DON_GIAM_GIA
ON HOADON
INSTEAD OF INSERT
AS
DECLARE @THOIGIAN DATETIME
DECLARE @MABAN INT
DECLARE @MAKH INT
DECLARE @MANV VARCHAR(50)
DECLARE @TRIGIA_TRUOC_GIAM_GIA MONEY 
DECLARE @MA_COUPON VARCHAR(50)
DECLARE @TRIGIA_SAU_GIAM_GIA MONEY
DECLARE @GIAM_GIA FLOAT 

SELECT @THOIGIAN = i.THOIGIAN FROM inserted AS i
SELECT @MABAN = i.MABAN FROM inserted AS i
SELECT @MAKH = i.MAKH FROM inserted AS i
SELECT @MANV = i.MANV FROM inserted AS i
SELECT @TRIGIA_TRUOC_GIAM_GIA = i.TRIGIA_TRUOC_GIAM_GIA FROM inserted AS i
SELECT @MA_COUPON = i.MA_COUPON FROM inserted AS i
SELECT @GIAM_GIA =  GIAM_GIA FROM COUPON WHERE MA_COUPON = @MA_COUPON

BEGIN 
	IF @GIAM_GIA IS NULL
		INSERT INTO HOADON VALUES(@THOIGIAN, @MABAN, @MAKH, @MANV, @TRIGIA_TRUOC_GIAM_GIA, @MA_COUPON, @TRIGIA_TRUOC_GIAM_GIA)
	ELSE
		BEGIN
			IF @GIAM_GIA < 1
				INSERT INTO HOADON VALUES(@THOIGIAN, @MABAN, @MAKH, @MANV, @TRIGIA_TRUOC_GIAM_GIA, @MA_COUPON, (1 - @GIAM_GIA)* @TRIGIA_TRUOC_GIAM_GIA)
			ELSE
				INSERT INTO HOADON VALUES(@THOIGIAN, @MABAN, @MAKH, @MANV, @TRIGIA_TRUOC_GIAM_GIA, @MA_COUPON, @TRIGIA_TRUOC_GIAM_GIA - @GIAM_GIA )
		END		
END


--2. TĂNG SỐ LẦN SỬ DỤNG COUPON
CREATE OR ALTER TRIGGER TANG_SO_LAN_SD_COUPON
ON HOADON
AFTER INSERT 
AS
DECLARE @MA_COUPON VARCHAR(50)
DECLARE @MAKH INT 

SELECT @MA_COUPON = i.MA_COUPON FROM inserted AS i
SELECT @MAKH = i.MAKH FROM inserted AS i

BEGIN	
	IF @MA_COUPON IS NOT NULL
		BEGIN
			UPDATE COUPON_DA_SU_DUNG
			SET SO_LAN = SO_LAN + 1
			WHERE MAKH = @MAKH AND MA_COUPON = @MA_COUPON
		END
END


--3. TĂNG SỐ LƯỢNG TRONG KHO HÀNG SAU KHI MUA NGUYÊN LIỆU
CREATE OR ALTER TRIGGER UPDATE_KHOHANG
ON CHI_TIEU
AFTER INSERT
AS
DECLARE @TEN_NGUYEN_LIEU VARCHAR(50)
DECLARE @SOLUONG INT 

SELECT @TEN_NGUYEN_LIEU = i.TEN_NGUYEN_LIEU FROM inserted AS i
SELECT @SOLUONG = i.SOLUONG FROM inserted AS i

BEGIN 
	UPDATE KHOHANG 
	SET SOLUONG = SOLUONG + @SOLUONG
	WHERE TEN_NGUYEN_LIEU = @TEN_NGUYEN_LIEU
END


--4. CHUYỂN TRẠNG THÁI BÀN
CREATE OR ALTER TRIGGER CHUYEN_TRANG_THAI_BAN
ON DATBAN
AFTER INSERT 
AS 
DECLARE @MABAN INT 
DECLARE @NGAY DATE
DECLARE @THOIGIAN TIME

SELECT @MABAN = i.MABAN FROM inserted AS i
SELECT @NGAY = i.NGAY FROM inserted AS i
SELECT @THOIGIAN = i.THOIGIAN FROM inserted AS i
BEGIN 
	UPDATE CHI_TIET_BAN
	SET TINHTRANG = 1 
	WHERE MABAN = @MABAN AND NGAY = @NGAY AND THOIGIAN = @THOIGIAN
END


--5. XÓA MÓN ĂN
CREATE OR ALTER TRIGGER XOA_MON_AN
ON MON_AN
AFTER DELETE 
AS
DECLARE @TEN_MON_AN VARCHAR(50)
DECLARE @GIA MONEY

SELECT @TEN_MON_AN = i.TEN_MON_AN FROM deleted AS i
SELECT @GIA = i.GIA FROM deleted AS i

BEGIN
	IF @TEN_MON_AN IS NOT NULL
		INSERT INTO THAY_DOI VALUES(@TEN_MON_AN, 'TEN_MON_AN', @TEN_MON_AN, NULL, SYSDATETIME())
	IF @GIA IS NOT NULL
		INSERT INTO THAY_DOI VALUES(@TEN_MON_AN, 'GIA', @GIA, NULL, SYSDATETIME())
END


--6. THÊM HOẶC SỬA MÓN ĂN
CREATE OR ALTER TRIGGER UPDATE_INSERT_MON_AN
ON MON_AN
AFTER UPDATE, INSERT
AS
DECLARE @TEN_MON_AN_MOI VARCHAR(50)
DECLARE @GIA_MOI MONEY

DECLARE @TEN_MON_AN_CU VARCHAR(50)
DECLARE @GIA_CU VARCHAR(50)

SELECT @TEN_MON_AN_MOI = i.TEN_MON_AN FROM inserted AS i
SELECT @GIA_MOI = i.GIA FROM inserted AS i

SELECT @TEN_MON_AN_CU = i.TEN_MON_AN FROM deleted AS i
SELECT @GIA_CU = I.GIA FROM deleted AS i

BEGIN
	IF @TEN_MON_AN_MOI <> @TEN_MON_AN_CU OR (@TEN_MON_AN_CU IS NULL AND @TEN_MON_AN_MOI IS NOT NULL) OR (@TEN_MON_AN_CU IS NOT NULL AND @TEN_MON_AN_MOI IS NULL)
		INSERT INTO THAY_DOI VALUES(@TEN_MON_AN_MOI, 'TEN_MON_AN', @TEN_MON_AN_CU, @TEN_MON_AN_MOI, SYSDATETIME())

	IF @GIA_MOI <> @GIA_CU OR (@GIA_MOI IS NULL AND @GIA_CU IS NOT NULL) OR (@GIA_MOI IS NOT NULL AND @GIA_CU IS NULL)
		INSERT INTO THAY_DOI VALUES(@TEN_MON_AN_MOI, 'GIA', @GIA_CU, @GIA_MOI, SYSDATETIME())
END


