--VIEW

--1. CÁC MÓN ĂN BÁN ĐƯỢC ÍT NHẤT
CREATE OR ALTER VIEW MON_AN_IT_NHAT AS
SELECT TOP(5) MON_AN.TEN_MON_AN,GIA, SUM(SOLUONG) AS SO_LUONG 
FROM CTHD 
FULL JOIN MON_AN ON CTHD.TEN_MON_AN = MON_AN.TEN_MON_AN
GROUP BY MON_AN.TEN_MON_AN,GIA
ORDER BY SUM(SOLUONG) ASC


--2. TOP 5 NGUYÊN LIỆU ĐƯỢC SỬ DỤNG TRONG NHIỀU MÓN ĂN NHẤT
CREATE OR ALTER VIEW NGUYEN_LIEU_NHIEU_NHAT AS
SELECT TOP(5) NGUYENLIEU.TEN_NGUYEN_LIEU, MA_CUNGCAP, COUNT(NGUYENLIEU.TEN_NGUYEN_LIEU) AS SO_MON_AN
FROM CONGTHUC
JOIN NGUYENLIEU ON NGUYENLIEU.TEN_NGUYEN_LIEU = CONGTHUC.TEN_NGUYEN_LIEU
GROUP BY NGUYENLIEU.TEN_NGUYEN_LIEU, MA_CUNGCAP
ORDER BY SO_MON_AN DESC


--3. DOANH THU CỦA TỪNG THÁNG
CREATE OR ALTER VIEW DOANHTHU AS
SELECT YEAR(THOIGIAN) AS NAM, MONTH(THOIGIAN) AS THANG, SUM(TRIGIA_SAU_GIAM_GIA) AS TONG_DOANH_THU
FROM HOADON
GROUP BY YEAR(THOIGIAN), MONTH(THOIGIAN)


--4. CHI TIÊU CỦA TỪNG THÁNG
CREATE OR ALTER VIEW TONGCHITIEU AS
SELECT YEAR(THOIGIAN) AS NAM, MONTH(THOIGIAN) AS THANG, SUM(GIA) AS TONG_CHI_TIEU
FROM CHI_TIEU
GROUP BY YEAR(THOIGIAN), MONTH(THOIGIAN)


--5. LƯƠNG CỦA CÁC NHÂN VIÊN
CREATE OR ALTER VIEW LUONGNHANVIEN AS
WITH TONG_SO_CA_LAM AS
(	
	SELECT  YEAR(NGAY_KETTHUC) AS NAM, MONTH(NGAY_KETTHUC) AS THANG, NHANVIEN.MANV, COUNT(CA)*7 AS SO_CA_DANG_KY 
	FROM NHANVIEN
	FULL JOIN CA_LAM_NHAN_VIEN ON CA_LAM_NHAN_VIEN.MANV = NHANVIEN.MANV
	FULL JOIN CA_LAM ON CA_LAM_NHAN_VIEN.MA_CA_LAM = CA_LAM.MA_CA_LAM
	GROUP BY YEAR(NGAY_KETTHUC),MONTH(NGAY_KETTHUC), NHANVIEN.MANV 
)
,
TONG_SO_CA_NGHI AS
(
	SELECT YEAR(NGAY_NGHI) AS NAM, MONTH(NGAY_NGHI) AS THANG, MANV, COUNT(NGAY_NGHI) AS SO_CA_NGHI 
	FROM NGAYNGHI
	GROUP BY YEAR(NGAY_NGHI), MONTH(NGAY_NGHI), MANV
)
SELECT TONG_SO_CA_LAM.NAM, TONG_SO_CA_LAM.THANG, TONG_SO_CA_LAM.MANV, SO_CA_DANG_KY, COALESCE(SO_CA_NGHI,0) AS SO_CA_NGHI,
SO_CA_DANG_KY - COALESCE(SO_CA_NGHI,0) AS TONG_CA, LUONG, LUONG * (SO_CA_DANG_KY - COALESCE(SO_CA_NGHI,0)) AS TONGLUONG
FROM TONG_SO_CA_LAM 
FULL JOIN TONG_SO_CA_NGHI ON TONG_SO_CA_LAM.NAM = TONG_SO_CA_NGHI.NAM 
AND TONG_SO_CA_LAM.THANG = TONG_SO_CA_NGHI.THANG 
AND TONG_SO_CA_LAM.MANV = TONG_SO_CA_NGHI.MANV 
FULL JOIN NHANVIEN ON TONG_SO_CA_LAM.MANV = NHANVIEN.MANV


--6. LỢI NHUẬN CỦA TỪNG THÁNG
CREATE OR ALTER VIEW LOINHUAN AS
WITH T AS 
(
	SELECT NAM, THANG, SUM(TONGLUONG) AS TONG_LUONG
	FROM LUONGNHANVIEN
	GROUP BY NAM, THANG
)
SELECT T.NAM, T.THANG, TONG_DOANH_THU - TONG_CHI_TIEU - TONG_LUONG AS TONG_LOI_NHUAN 
FROM T 
JOIN TONGCHITIEU ON T.NAM = TONGCHITIEU.NAM AND T.THANG = TONGCHITIEU.THANG 
JOIN DOANHTHU ON DOANHTHU.NAM = T.NAM AND DOANHTHU.THANG = T.THANG


